import React from 'react';
import { Trophy, Medal, Award, Users, DollarSign } from 'lucide-react';

export function ReferralLeaderboard() {
  const topReferrers = [
    {
      rank: 1,
      username: 'cryptoking',
      referrals: 156,
      volume: 1250000,
      rewards: 45000,
      badge: 'Diamond'
    },
    {
      rank: 2,
      username: 'moonwhale',
      referrals: 124,
      volume: 890000,
      rewards: 32000,
      badge: 'Platinum'
    },
    {
      rank: 3,
      username: 'degen007',
      referrals: 98,
      volume: 670000,
      rewards: 28000,
      badge: 'Gold'
    },
    {
      rank: 4,
      username: 'tokenmaster',
      referrals: 87,
      volume: 540000,
      rewards: 22000,
      badge: 'Gold'
    },
    {
      rank: 5,
      username: 'launchboss',
      referrals: 76,
      volume: 450000,
      rewards: 19000,
      badge: 'Silver'
    }
  ];

  const getRankIcon = (rank: number) => {
    switch (rank) {
      case 1: return <Trophy className="h-5 w-5 text-yellow-400" />;
      case 2: return <Medal className="h-5 w-5 text-gray-400" />;
      case 3: return <Award className="h-5 w-5 text-orange-400" />;
      default: return <div className="w-5 h-5 flex items-center justify-center text-sm font-bold text-text-muted">#{rank}</div>;
    }
  };

  const getBadgeColor = (badge: string) => {
    switch (badge) {
      case 'Diamond': return 'text-cyan-400 bg-cyan-400/20';
      case 'Platinum': return 'text-gray-300 bg-gray-300/20';
      case 'Gold': return 'text-yellow-400 bg-yellow-400/20';
      case 'Silver': return 'text-gray-400 bg-gray-400/20';
      default: return 'text-text-muted bg-surface-hover';
    }
  };

  const formatNumber = (num: number) => {
    if (num >= 1e6) return `${(num / 1e6).toFixed(1)}M`;
    if (num >= 1e3) return `${(num / 1e3).toFixed(1)}K`;
    return num.toString();
  };

  return (
    <div className="space-y-6">
      {/* Your Position */}
      <div className="bg-surface/80 backdrop-blur-sm rounded-lg border border-border p-6">
        <h3 className="text-lg font-semibold mb-4">Your Position</h3>
        <div className="bg-primary/10 border border-primary/20 rounded-lg p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 bg-primary/20 rounded-lg flex items-center justify-center">
                <span className="text-lg font-bold">#12</span>
              </div>
              <div>
                <div className="font-semibold">You (yourhandle)</div>
                <div className="text-sm text-text-muted">23 referrals • $156K volume</div>
              </div>
            </div>
            <div className="text-right">
              <div className="text-2xl font-bold text-primary">2,450</div>
              <div className="text-sm text-text-muted">$OKIE earned</div>
            </div>
          </div>
        </div>
      </div>

      {/* Leaderboard */}
      <div className="bg-surface/80 backdrop-blur-sm rounded-lg border border-border overflow-hidden">
        <div className="p-6 border-b border-border">
          <h3 className="text-lg font-semibold">Top Referrers</h3>
          <p className="text-text-muted text-sm mt-1">
            Rankings based on total volume generated by referrals
          </p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-surface-hover">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                  Rank
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                  User
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                  Referrals
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                  Volume
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                  Rewards
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                  Badge
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {topReferrers.map((referrer) => (
                <tr key={referrer.rank} className="hover:bg-surface-hover transition-colors">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      {getRankIcon(referrer.rank)}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-8 h-8 bg-gradient-to-br from-primary/20 to-accent/20 rounded-lg flex items-center justify-center mr-3">
                        <span className="text-sm font-bold">{referrer.username.charAt(0).toUpperCase()}</span>
                      </div>
                      <div className="font-medium">{referrer.username}</div>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center text-sm">
                      <Users className="h-4 w-4 text-text-muted mr-1" />
                      {referrer.referrals}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center text-sm">
                      <DollarSign className="h-4 w-4 text-text-muted mr-1" />
                      {formatNumber(referrer.volume)}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-primary">
                      {formatNumber(referrer.rewards)} $OKIE
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getBadgeColor(referrer.badge)}`}>
                      {referrer.badge}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Badges Information */}
      <div className="bg-surface/80 backdrop-blur-sm rounded-lg border border-border p-6">
        <h3 className="text-lg font-semibold mb-4">Referral Badges</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { name: 'Bronze', requirement: '10+ referrals', multiplier: '1x', color: 'text-orange-600' },
            { name: 'Silver', requirement: '25+ referrals', multiplier: '1.2x', color: 'text-gray-400' },
            { name: 'Gold', requirement: '50+ referrals', multiplier: '1.5x', color: 'text-yellow-400' },
            { name: 'Diamond', requirement: '100+ referrals', multiplier: '2x', color: 'text-cyan-400' }
          ].map((badge, index) => (
            <div key={index} className="bg-surface-hover rounded-lg p-4 text-center">
              <div className={`text-lg font-bold ${badge.color} mb-2`}>
                {badge.name}
              </div>
              <div className="text-sm text-text-muted mb-1">
                {badge.requirement}
              </div>
              <div className="text-sm font-medium">
                {badge.multiplier} rewards
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}